---

- name: install Apacher2
  hosts: all
  become: true
  tasks:

  - name: Install, configure and start Apacher2 on Debian OS
    block:
      - name: install Apache2 in Debian os
        apt:
          name: apache2
          state: latest
      

      - name: start nginx
        service:
          name: apache2
          state: started
            
      - name: copy index.html
        copy:
          src: ./index.html
          dest: /var/www/html/index.html
        notify: 
          - restart Debian Apache2

    when: ansible_facts["os_family"] == 'Debian'


  - name: Install, configure and start Apache2 in RedHat OS
    block:
      - name: install Apache2
        apt:
          name: httpd
          state: latest

      - name: start nginx
        service:
          name: httpd
          state: started

      - name: copy index.html
        copy:
          src: ./index.html
          dest: /var/www/html/index.html
        notify:
          - restart RedHat Apache2

    when: ansible_facts["os_family"] == 'RadHat'
      
  handlers: 
    - name: restart Debian Apache2
      service:
        name: apache2
        state: restarted
      
    - name: restart RedHat Apache2
      service:
        name: httpd
        state: restarted

